<a href="https://colab.research.google.com/github/ranjan1311/hello-world/blob/main/ISLR2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2. Statistical Learning 
Ques- 07 KNN

Suppose we wish to use this data set to make a prediction for Y when
X1 = X2 = X3 = 0 using K-nearest neighbors.
(a) Compute the Euclidean distance between each observation and
the test point, X1 = X2 = X3 = 0.
(b) What is our prediction with K = 1? Why?
(c) What is our prediction with K = 3? Why?
(d) If the Bayes decision boundary in this problem is highly nonlinear, then would we expect the best value for K to be large or
small? Why?

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [16]:
df = pd.DataFrame({'Obs': [1, 2, 3, 4, 5, 6],
                   'X1': [0, 2, 0, 0, -1, 1],
                   'X2': [3, 0, 1, 1, 0, -1],
                   'X3': [0, 0, 3, 2, 1, 1],
                   'Y': ['Red', 'Red', 'Red', 'Green', 'Green', 'Red']})

df
(np.sum(df[['X1', 'X2', 'X3']]**2))**0.5

X1    2.449490
X2    3.464102
X3    3.872983
dtype: float64

In [3]:
# (a) Compute the Euclidean distance between each observation and the test point,X1 =X2 =X3 =0. 

def euclidian_dist(x):
    """Compute the row-wise euclidean distance
    from the origin"""
    return (np.sum(x**2, axis=1))**0.5

euc_dist = pd.DataFrame({'EuclideanDist': euclidian_dist(df[['X1', 'X2', 'X3']])})
df_euc = pd.concat([df, euc_dist], axis=1)
df_euc

   Obs  X1  X2  X3      Y  EuclideanDist
0    1   0   3   0    Red       3.000000
1    2   2   0   0    Red       2.000000
2    3   0   1   3    Red       3.162278
3    4   0   1   2  Green       2.236068
4    5  -1   0   1  Green       1.414214
5    6   1  -1   1    Red       1.732051

In [4]:
# (b) What is our prediction with K = 1? Why?  

K = 1
df_euc.nsmallest(K, 'EuclideanDist')

# Our prediction is Y=Green because that is the response value of the 
# first nearest neighbour to the point X1 = X2 = X3 = 0

   Obs  X1  X2  X3      Y  EuclideanDist
4    5  -1   0   1  Green       1.414214

In [17]:
# (c) What is our prediction with K = 3? Why?  

K = 3
df_euc.nsmallest(K, 'EuclideanDist')

# Red, because majority of the 3 nearest neighbours are Red.

   Obs  X1  X2  X3      Y  EuclideanDist
4    5  -1   0   1  Green       1.414214
5    6   1  -1   1    Red       1.732051
1    2   2   0   0    Red       2.000000

In [ ]:
#(d) If the Bayes decision boundary in this problem is highly non-linear, then would we expect the best value for K to be large or small? Why?

#Small. A smaller value of K results in a more flexible classification model because the prediciton is based upon a smaller subset of all observations in the dataset.

# Applied
Ques - 08